### ISSUE TITLE
How do I set up local data for run backtest local?

### ISSUE THREAD

**Issue by miaekim** [QuantConnect/lean-cli#1]
I need some guidance for https://github.com/QuantConnect/lean-cli#lean-backtest.
I guess we need local data set up to use this command but the above doc doesn't have instruction to set up local data.

**Comment by jaredbroad** [comment]
Hey Miaekim - welcome to QC! Glad you're an early adopter! This is pre-release software at the moment please give us another week and the docs will be done and it'll be ready to read.

**Comment by miaekim** [comment]
Can `lean data generate` generate fundamental data as well?

**Comment by jmerle** [comment]
No, `lean data generate` can only generate coarse equity data. You can create a feature requests for it in the [QuantConnect/Lean](https://github.com/QuantConnect/Lean) repository, which is where the random data generator is hosted.

As for the original post:
Sorry for not getting back to you in time, the publicly announced beta release is a little delayed, but we do now have [documentation on how local data is stored](https://www.quantconnect.com/docs/v2/lean-cli/user-guides/local-data) and [tutorials on how to source local data](https://www.quantconnect.com/docs/v2/lean-cli/tutorials/local-data).

**Comment by miaekim** [comment]
I still have some issues with it.  I am currently using Linux and followed [Lean README.md](https://github.com/QuantConnect/Lean/blob/master/.vscode/readme.md). Therefore, I didn't set up any file sharing.
Let's say I use generated data like below. `~/qc` is my `lean init` directory.

```
~/qc ❯ lean data generate --start 20200101  --symbol-count=50  --resolution=Daily --include-coarse True
```
The data is stored under `~/qc/data`.

When I run backtest, it runs docker container.
```
❯ lean backtest "myTest"
```
The backtest tries to read images inside the docker container saying
```
ApiDataProvider.Fetch(): failed to parse key /Lean/Data/equity/usa/fundamental/coarse/20191231.csv
LeanData.TryParsePath(): Error encountered while parsing the path Lean/Data/equity/usa/fundamental/coarse/20200102. Error:
System.ArgumentException: Requested value 'fundamental' was not found.
```

Maybe tutorial could include sharing downloaded files with docker container, or having the option to provide data mount path for backtesting, etc..?

**Comment by jmerle** [comment]
You appear to be using the ApiDataProvider, which doesn't support coarse/fundamental data because we currently cannot redistribute that data. Can you try changing `data-provider` to `QuantConnect.Lean.Engine.DataFeeds.DefaultDataProvider` in your `lean.json` file and run the backtest again?

**Comment by miaekim** [comment]
Hello jmerle,

I don't see the above error anymore, but I see zero counts in the log. 

I generated data 

```
❯ lean data generate --start 20200101  --symbol-count=5000  --resolution=Dail
```

```python
class NCAVsimple(QCAlgorithm):
    def Initialize(self):
        #rebalancing should occur in July
        self.SetStartDate(2020, 1, 1)  
        self.SetCash(100000) 
        self.UniverseSettings.Resolution = Resolution.Daily
  
       .... 
        self.yearly_rebalance = False
        self.AddUniverse(self.CoarseSelectionFunction,self.FineSelectionFunction)
        self.Schedule.On(self.DateRules.MonthEnd(self.symbol), self.TimeRules.AfterMarketOpen(self.symbol), self.rebalance)
        
    def CoarseSelectionFunction(self, coarse):
        if self.yearly_rebalance:
            # drop stocks which have no fundamental data or have low price
            self.filtered_coarse = [x.Symbol for x in coarse if (x.HasFundamentalData) and x.Market == 'usa']
            self.Debug("coarse: " + str(len(self.filtered_coarse)))
            return self.filtered_coarse
        else: 
            return []      
...
 
    def FineSelectionFunction(self, fine):
        if self.yearly_rebalance:
            fine = [x for x in fine if x.EarningReports.BasicAverageShares.ThreeMonths > 0 and x.MarketCap != 0 and x.ValuationRatios.WorkingCapitalPerShare != 0]
            self.Debug("Fine: " + str(len(fine)))
```

```
❯ lean backtest "NCAV_simple" --update | less
20210325 23:26:12.648 TRACE:: Debug: Rebalance2020-06-30 09:30:00
coarse: 0
Fine: 0
```

But when I run exact same code on the cloud,  I could see counts.
```                         
❯ lean cloud backtest "NCAV_simple"  
coarse: 5594
Fine: 3866
```

**Comment by jmerle** [comment]
The reason that works in the cloud is that the cloud does have fundamental data, while the random data generator can only generate coarse data. This means `x.HasFundamentalData` is `False` for all symbols in the coarse universe, resulting in "coarse: 0" and "Fine: 0" in your algorithm.

**Comment by miaekim** [comment]
I see, is there a way to import external fundamental data like yahoo finance to lean-cli/data folder?

**Comment by jmerle** [comment]
No, there's no automated way to do that. LEAN is made to read fundamental data in MorningStar's data format from the data folder, and we don't currently have any open-source tools to set that up yourself locally.

**Comment by jmerle** [comment]
It's been more than three months since the last activity on this issue and the original questions have been answered, so I'm closing it. Please open a new issue if you're still facing issues.

**Comment by tommedema** [comment]
> Sorry for not getting back to you in time, the publicly announced beta release is a little delayed, but we do now have [documentation on how local data is stored](https://www.quantconnect.com/docs/v2/lean-cli/user-guides/local-data) and [tutorials on how to source local data](https://www.quantconnect.com/docs/v2/lean-cli/tutorials/local-data).

any updated links here? they are dead

**Comment by DerekMelchin** [comment]
@tommedema Checkout the Datasets chapter in the CLI docs
https://www.quantconnect.com/docs/v2/lean-cli/datasets/format-and-storage
