### ISSUE TITLE
fetch the latest LEAN repository in the directory created by lean init

### ISSUE THREAD

**Issue by fishstoryyy** [QuantConnect/lean-cli#11]
Hi,

Is there a way to update the directory created by `lean init` with the latest LEAN repository? Thank you.

**Comment by jmerle** [comment]
Hi fishstoryyy,

What do you mean with "to update the directory created by `lean init` with the latest LEAN repository"? If you use the CLI you run LEAN using the Docker images on DockerHub and use our PyPI and NuGet packages to get autocomplete. There is no need to have the entire LEAN repository on your local drive.

**Comment by fishstoryyy** [comment]
Hi Jasper,

Thanks. Yes my main concern is on autocomplete. My initial thought was that `lean init` will fetch something from the LEAN repository, so I wasn't sure if `lean init` will return something new in case the repository is updated.

**Comment by jmerle** [comment]
The `lean init` command fetches the LEAN launcher configuration and example data from the LEAN repository, it does not affect autocomplete. I just updated the [autocomplete documentation](https://www.lean.io/docs/lean-cli/tutorials/local-autocomplete#08-Staying-up-to-date) to include steps on how to keep C# and Python autocomplete up-to-date, I hope that helps.

**Comment by fishstoryyy** [comment]
Thank you very much! It helps.
