### ISSUE TITLE
"No suitable Java Virtual Machine" Error on IB Deployment under macOS (M1 Chip)

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#114]
The IB Gateway shell script checks the Java version installed and it only accepts 1.8.0_152.
However, the Lean docker image for M1 is only pre-installed with Java 1.8.0_312.

Ref.: Community Forum:
[Lean local live trading IBGateway error: No suitable Java Virtual Machine could be found on your system.?](https://www.quantconnect.com/forum/discussion/13938/lean-local-live-trading-ibgateway-error-no-suitable-java-virtual-machine-could-be-found-on-your-system/p1)

Potential solution:
Update ARM image to include Java VM 1.8.0_152.

**Comment by jmullen** [comment]
It appears this does not fix the issue for the M2 chip.
