### ISSUE TITLE
Download logs of cloud tasks

### ISSUE THREAD

**Issue by anaderi** [QuantConnect/lean-cli#12]
I'd like to be able to download logs of either cloud backtesting or cloud live algorithm running. I haven't found any examples/hints if it is possible now, thus please consider this issue as a feature request, if it is the case indeed. I.e., if one could run 

    lean cloud logs [--live|--backtest] --project MyProject [--name RunName]

it would be awesome.

**Comment by jmerle** [comment]
Unfortunately this feature request cannot be implemented. A feature like this would make it possible to export data, which goes against QuantConnect's data agreements.

If you want local logging I advise you to run LEAN locally and use the CLI's [data downloading](https://www.lean.io/docs/lean-cli/user-guides/local-data#03-QuantConnect-Data-Library) feature to purchase and download the data your algorithm needs. This feature allows you to download the same data that is available on QuantConnect, so your algorithm should run exactly the same, without any of the logging restrictions of the cloud.
