### ISSUE TITLE
Newly introduced, vaguely documented, requirements for brokerage "organization" / "module subscription" when live trading..?

### ISSUE THREAD

**Issue by lucasbrynte** [QuantConnect/lean-cli#120]
Hi!

With the latest Docker version of Lean and latest Lean CLI version, I can no longer use Lean CLI for live trading on the Bitfinex exchange without selecting an "organization" with a subscription for the Bitfinex "module".

More concretely, I've stumbled across the following error message when attempted to run the "lean live" command (in non-interactive mode) as before:
```
Error: Please configure the following missing property in /home/lucas/qc/lean.json:
- bitfinex-organization
```
In the interactive mode, my personal organization "Lucas Brynte" gets automatically selected, and after providing a Bitfinex API key and API secret, the following lines are printed out:
```
Downloading 'QuantConnect.BitfinexBrokerage.2.5.14331.nupkg'
Error: Module subscription not found, please update your preferences in www.quantconnect.com/pricing
```

It seems to me that there was a change on June 16, by commit 33003fd, resulting in the new behavior, and that one is now required to subscribe to some Quantconnect product in order to do local live trading with Lean CLI. Is this correctly understood and an intended change? I can see in Step 3 on [this page](https://www.quantconnect.com/docs/v2/lean-cli/live-trading/bitfinex) that "a subscription for the Bitfinex module" is indeed required, but I am clueless as to what product that refers to exactly. I find it hard to believe that local live trading with Lean CLI would now require a live Quantconnect server instance after all..?

Best Regards,
Lucas

**Comment by lucasbrynte** [comment]
@rjra2611 I would be much grateful if you could perhaps enlighten me on the matter (saw your ID on the commit mentioned above).

//Lucas

**Comment by jaredbroad** [comment]
Hi @lucasbrynte, 

We plan to make the VSCode plugin work locally so you'll have local charting; and charge for a Seat  (Researcher, Team, Trading Firm) for the local installation. This wouldn't include any server resources cost as you're on your own hardware. This will harness the CLI to execute the brokerages etc. We're hoping to make the seat cost cover the team costs as there are significant salaries for the maintenance of the software, whether in the cloud or locally.

Specifically, above, the error is saying you don't have a license to that software (the brokerage plugin to LEAN). This isn't a cloud resource but the brokerage plugin software. It's an older complicated pricing model we'll deprecate shortly in favor of the simpler seat model. 

Thanks
Jared

**Comment by lucasbrynte** [comment]
Hi Jared, thanks for the quick feedback!

So if I understand correctly, the future plan is to require one of the
Seats mentioned for use of either the VSCode plugin, enabling local
charting, or for use of the brokerage plugins.

Could you clarify what the current requirements are? Would one of the Seats
give me access to the brokerage plugin already?

A related question - can I use more than one local live trading instance
with a single Seat? (Each requiring the brokerage plugin)

//Lucas


Den ons 27 juli 2022 21:55Jared ***@***.***> skrev:

**Comment by rjra2611** [comment]
Hey Lucas, getting 1 seat license including the brokerage(s) add-on will give you access to live locally using the CLI with that brokerage(s).

> A related question - can I use more than one local live trading instance with a single Seat? (Each requiring the brokerage plugin)

Sure, there isn't any restriction on the number of local instances you can have as long as you are subscribed to the required brokerage

Let me know if this clears your doubts and I'll close this issue, thanks
