### ISSUE TITLE
Updating local libraries fails

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [QuantConnect/lean-cli#141]
After updating lean, I checked my notebooks and they are indeed running Python `3.8.13`, and Tensorflow `2.9.1`.

I typically run a debugger locally through VS Code (doesn't hook into the Docker instance) when testing scripts; I was using an older version of Tensorflow in my system installation so I decided to upgrade to match the version in the Docker instance.

However when I ran `lean library add "Project" tensorflow --version 2.9.1` I received the following error:

> Error: Version 2.9.1 of the tensorflow package is not compatible with Python 3.6.8

I would expect the install to work smoothly, but it looks like it's referencing an older version of Python. My local system setup is using `3.8.13`, and apparently so is the Docker instance, but adding libraries does something different.

The problem now is that my requirements.txt has regressed to using Tensorflow `2.6` and I'm getting errors when importing tensorflow in scripts.

**Comment by Martin-Molinero** [comment]
Hey @JakeTheSnake3p0! Thank you for the report, and sorry for the inconvenience. Believe this is fixed by https://github.com/QuantConnect/lean-cli/pull/140, `lean` version 1.0.104. Do you mind retesting using the latest version?

**Comment by JakeTheSnake3p0** [comment]
For some reason I ended up needing to completely wipe out my Python installation through anaconda and reinstall 3.10.

I noticed that when I got to running research, I needed to manually run "lean library add" for a bunch of libraries in my requirements.txt. It would be nice if there was a way to run "lean library update --all" to update all libraries given the current python version.

During a dependency error when attempting to run research, somewhere in the verbose logs I see the following:

```
'volumes': {
      'C:\\Users\\me\\Documents\\git-repositories\\lean-bot\\data': {'bind': '/Lean/Data', 'mode': 'rw'},
      'C:\\Users\\me\\AppData\\Local\\Temp\\lean-cli-71o3058q': {'bind': '/Results', 'mode': 'rw'},
      'C:\\Users\\me\\Documents\\git-repositories\\lean-bot\\Inference\\storage': {'bind': '/Storage', 'mode': 'rw'},
      'C:\\Users\\me\\Documents\\git-repositories\\lean-bot\\Inference': {'bind': '/Lean/Launcher/bin/Debug/Notebooks', 'mode': 'rw'},
      'C:\\Users\\me\\Documents\\git-repositories\\lean-bot\\Library': {'bind': '/Library', 'mode': 'rw'},
      'lean_cli_pip': {'bind': '/root/.cache/pip', 'mode': 'rw'},
      'lean_cli_python_bc6211fc52aa8161b4a87d04b079ddbe': {'bind': '/root/.local/lib/python3.8/site-packages', 'mode': 'rw'}
  },
```

Notice the reference to `python3.8`. As it turns out, that's what the Jupyter notebook shows as well. I ran the `lean research` command through an activated anaconda environment of `3.10`.

**Comment by Martin-Molinero** [comment]
Hey @JakeTheSnake3p0! 
> Notice the reference to python3.8. As it turns out, that's what the Jupyter notebook shows as well. I ran the lean research command through an activated anaconda environment of 3.10.

By default, the notebook will run using the lean base images which were using python 3.6 and now are running with python 3.8.13. See https://github.com/QuantConnect/Lean/blob/master/DockerfileJupyter. You can override the image used with `lean config`.

Is it working correctly for you now?

**Comment by JakeTheSnake3p0** [comment]
Yes, everything is working now - good to know it's intentional. All of the libraries I really care about (ex., tensorflow) seem to be using up to date versions so all is good.
