### ISSUE TITLE
Lean cloud push/pull overwrites config data of project

### ISSUE THREAD

**Issue by rjra2611** [QuantConnect/lean-cli#161]
`Lean cloud push` overwrites the cloud project config.json with local config.json

![image (2)](https://user-images.githubusercontent.com/28739120/191268777-d3879536-64b2-43d4-8282-41977e8f6518.png)

`Lean cloud pull` overwrites the local project config.json with cloud config.json

![image](https://user-images.githubusercontent.com/28739120/191268584-cd77d9e2-7f15-4001-9719-b183658bd775.png)

**Comment by Martin-Molinero** [comment]
Expected behavior as a force push/pull
