### ISSUE TITLE
Cant login to IB with local live trading

### ISSUE THREAD

**Issue by Fschoeller** [QuantConnect/lean-cli#17]
When running `lean live algo` , lean gets stuck on login, specifically the line `Click button: [Paper Log In]` .
The log says `InteractiveBrokersBrokerage.CheckIbAutomaterError(): InitializationTimeout - The IBAutomater initialization timed out`

**Comment by jmerle** [comment]
We recently made a change which should fix this error.. Can you try running `lean live <project name> --update` to ensure you are using the latest version and see if the error still occurs? If it does, it'd be very helpful if you can share the full logs so we can figure out exactly where something it goes wrong.

**Comment by Fschoeller** [comment]
If it's helpful, here are the logs as files
[log.txt](https://github.com/QuantConnect/lean-cli/files/6671088/log.txt)
[main-log.txt](https://github.com/QuantConnect/lean-cli/files/6671086/main-log.txt)

**Comment by Fschoeller** [comment]
Any news?

**Comment by jmerle** [comment]
The issue is your username being longer than what the IBGateway version in the current Docker images support. This will be fixed in the next CLI update after https://github.com/QuantConnect/Lean/pull/5686 is merged.

**Comment by Martin-Molinero** [comment]
We will ship this later today 👍

**Comment by jmerle** [comment]
This should be fixed now. Can you try running `pip install --upgrade lean` and then `lean live <project name> --upgrade` and see if the error still occurs?

**Comment by Fschoeller** [comment]
Works now, thanks!
