### ISSUE TITLE
Can't use spaces in Python project library names

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#177]
In the readme, we have an example
```
$ lean library add "My Python Project" "Library/My Python Library"
```
but this throws 
> Error: 'My Python Library' is not a valid Python identifier, which is required for Python library projects to be importable

because `My Python Library` has spaces.

The CLI should detect the spaces and recommend removing them from the library name.

**Comment by LouisSzeto** [comment]
@DerekMelchin I can't reproduce the issue. 
```
PS C:\Users\user\Documents\LeanCLI> lean library add "Test Python" "Library/Test Library"
Adding Lean CLI library C:\Users\user\Documents\LeanCLI\Library\Test Library to project
C:\Users\user\Documents\LeanCLI\Test Python
```

Can you also provide the content of the `Library/My Python Library` project?

**Comment by LouisSzeto** [comment]
In project creation, the error will throw up for good already:
```
PS C:\Users\user\Documents\LeanCLI> lean project-create "Library/Test Library"
Error: 'Test Library' is not a valid Python identifier, which is required for Python library projects to be importable
```

**Comment by DerekMelchin** [comment]
Yes, this error message of 
```
Error: 'Test Library' is not a valid Python identifier, which is required for Python library projects to be importable
```
should be updated

**Comment by LouisSzeto** [comment]
Right, I mean in your original post you mentioned the error popped up by the command:
`lean library add "My Python Project" "Library/My Python Library"`
but this doesn't throw any error in my end. 

Only `lean project-create "Library/Test Library"` does thorw that error, and this error message is suitable in this context. I wonder if the content of your `"Library/Test Library"` is causing the error in your end.
