### ISSUE TITLE
Not stopping in VSCode breakpoints (v1.10)

### ISSUE THREAD

**Issue by cordmaur** [QuantConnect/lean-cli#18]
Hi,
My local lean was working fine in v1.05. Today, when I updated to lean 1.10 it is not stopping in the breakpoints when debugging using VSCode. I restarted the working directory and pulled all projects from the cloud again, but no changes. It connects to the port 5678 as expected and runs the code, but now it skips all breakpoints. Tried other solutions but none seems to work.
Any ideas?

Thanks,

**Comment by jmerle** [comment]
Hi cordmaur,

We recently made some changes to LEAN that change how Python algorithms are ran. Please run the `lean backtest` command with the `--update` flag, after that it should work again.

**Comment by cordmaur** [comment]
Thanks @jmerle , it is working again.
