### ISSUE TITLE
Backtest not reading Generated Data

### ISSUE THREAD

**Issue by cordmaur** [QuantConnect/lean-cli#19]
Hi, 
I tried to generate random data using lean data generate, but when I run the backtest, the newly generated ticker doesn't appear in the Universe Selection nor in the OnData feed, even if I add the equity manually.

I tried reseting the lean repository and updating the lean data generate as explained in https://github.com/QuantConnect/lean-cli/issues/3#issue-845886027. 

It raises an error at the end:
`20210622 18:14:08.080 TRACE:: LeanDataWriter.Write(): Created: ../../../Data/equity/usa/minute/ths/20210617_trade.zip
20210622 18:14:08.104 TRACE:: LeanDataWriter.Write(): Created: ../../../Data/equity/usa/minute/ths/20210618_trade.zip
20210622 18:14:08.128 TRACE:: LeanDataWriter.Write(): Created: ../../../Data/equity/usa/minute/ths/20210621_trade.zip
20210622 18:14:08.147 TRACE:: LeanDataWriter.Write(): Created: ../../../Data/equity/usa/minute/ths/20210622_trade.zip
20210622 18:14:08.172 TRACE:: LeanDataWriter.Write(): Created: ../../../Data/equity/usa/daily/ths.zip
   Symbol[1]: THS 2T Progress: 100.0% - Symbol data generation and output completed
Random data generation has completed.
Launching coarse data generator...
20210622 18:14:08.173 TRACE:: Config.Get(): Configuration key not found. Key: reserved-words-prefix - Using default value: quantconnect-
20210622 18:14:08.176 TRACE:: CoarseUniverseGeneratorProgram.ProcessDailyFolder(): Processing: /Lean/Data/equity/usa/daily
20210622 18:14:08.196 TRACE:: CoarseUniverseGeneratorProgram.PopulateSidContex(): Generating SID context from QuantQuote's map files.
20210622 18:14:08.209 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/vxxb.zip not found!
20210622 18:14:08.213 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/vxx.zip not found!
20210622 18:14:08.213 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker VXX not found!
20210622 18:14:08.213 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker VXXB not found!
20210622 18:14:08.286 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/vxx.zip not found!
20210622 18:14:08.286 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker VXX not found!
20210622 18:14:08.341 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/aol.zip not found!
20210622 18:14:08.344 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/twx.zip not found!
20210622 18:14:08.344 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker TWX not found!
20210622 18:14:08.344 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker AOL not found!
20210622 18:14:08.350 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/twx.zip not found!
20210622 18:14:08.350 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker TWX not found!
20210622 18:14:08.365 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/nb.zip not found!
20210622 18:14:08.424 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/nwsa.zip not found!
20210622 18:14:08.426 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/foxa.zip not found!
20210622 18:14:08.428 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/tfcfa.zip not found!
20210622 18:14:08.428 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker TFCFA not found!
20210622 18:14:08.428 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker FOXA not found!
20210622 18:14:08.428 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker NWSA not found!
20210622 18:14:08.441 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/spwr.zip not found!
20210622 18:14:08.442 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/spwra.zip not found!
20210622 18:14:08.442 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker SPWR not found!
20210622 18:14:08.442 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker SPWRA not found!
20210622 18:14:08.442 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker SPWR not found!
20210622 18:14:08.533 ERROR:: CoarseUniverseGeneratorProgram.Run(): ../../../Data/equity/usa/daily/qqqq.zip not found!
20210622 18:14:09.483 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker QQQQ not found!
20210622 18:14:10.415 ERROR:: CoarseUniverseGeneratorProgram.Run(): Daily data for ticker NB not found!
20210622 18:14:23.855 TRACE:: CoarseUniverseGeneratorProgram.Run(): Processed 1000 in 0:00:00.9406899 at 1063.05 files/second
20210622 18:14:24.743 TRACE:: CoarseUniverseGeneratorProgram.Run(): Processed 2000 in 0:00:01.8294276 at 1093.24 files/second
20210622 18:14:25.678 TRACE:: CoarseUniverseGeneratorProgram.Run(): Processed 3000 in 0:00:02.7642657 at 1085.28 files/second`

However, when I check the `minute `folder, the `fundamental/coarse` and the `map_files`, the new ticker appears normally. I don't understand what is missing for Lean to find it.

Any suggestions?

Thanks

**Comment by jmerle** [comment]
Hi cordmaur,

I just tried this locally and couldn't reproduce the issue. Can you try running LEAN with this algorithm and see if it's going through any data points? Make sure to set the start date and ticker to the details of your generated data.

```python
from AlgorithmImports import *


class PythonProject(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2020, 1, 1)
        self.SetCash(100000)
        self.SetBenchmark(lambda x: 0)
        self._symbol = self.AddEquity("QFD", Resolution.Minute).Symbol

    def OnData(self, data):
        if not self.Portfolio.Invested:
            self.SetHoldings(self._symbol, 1)
```

You should see something like "Processing total of 143,945 data points" a few lines above the statistics at the bottom of the backtest logs when you run this algorithm.

**Comment by cordmaur** [comment]
Hi @jmerle,

I created the data using:
`lean data generate --start=20210315 --symbol-count=1 --update`
And it created the ticker THS. 

I tested your algo and it worked. I realized that on the first day 20210315 this ticker does not appear in the Universe Coarse Selection (img bellow). But it does the following days. 

![image](https://user-images.githubusercontent.com/19617404/123004699-45e35600-d3b5-11eb-98c1-be611701d554.png)


I could fix my algo considering this.
Thanks,

**Comment by jmerle** [comment]
Hi cordmaur,

Sorry for the delay. The behavior you're observing is expected, coarse universe selection happens at midnight after a trading day, which means that in your example it triggers for the first time at 2021-03-15 00:00:00. Because your generated data starts at 2021-03-15 09:30:00, it is expected that it's only passed through your coarse selection function from 2021-03-16 00:00:00 onwards.

**Comment by cordmaur** [comment]
Thanks
