### ISSUE TITLE
Volume not mounted in Research container

### ISSUE THREAD

**Issue by teeling** [QuantConnect/lean-cli#190]
I'm trying to mount a local directory in the Research environment, to centralise common code that I use on all strategies.
In the config.json for the algo project, I have the following:

```
{
    "algorithm-language": "Python",
    "parameters": {},
    "description": "",
    "local-id": 1921689343,
    "docker": { "ports": { "999": "6006"}, "volumes": ["/LocalPath/includes/:/Lean/Launcher/bin/Debug/Notebooks/includes/"] }
}

```
The ports setting works, the container exposes the correct port as expected, but the volume does not mount.

I'm looking in to "https://github.com/QuantConnect/lean-cli/blob/0e081de8a5ded15b0862398fd2bf0f7c843180a2/lean/components/docker/lean_runner.py" and on line 222 we have:

```
        run_options: Dict[str, Any] = {
            "detach": detach,
            "commands": [],
            "environment": docker_project_config.get("environment", {}),
            "stop_signal": "SIGINT" if debugging_method is None else "SIGKILL",
            "mounts": [],
            "volumes": {},
            "ports": docker_project_config.get("ports", {})
        }
```

Should our mounts from the config.json not be read there?

Thanks!

**Comment by Martin-Molinero** [comment]
Hey @teeling!
> I'm trying to mount a local directory in the Research environment

sorry, this is currently not supported

> centralise common code that I use on all strategies.

This sounds like the project library feature which lean cli does handle, suggest taking a look at [lean library add](https://github.com/QuantConnect/lean-cli#lean-library-add) & [lean library remove](https://github.com/QuantConnect/lean-cli#lean-library-remove) & the [lean cli docs](https://www.lean.io/docs/v2/lean-cli/projects/libraries/project-libraries)

**Comment by teeling** [comment]
Hi @Martin-Molinero ,
Thanks for your reply! I see, I'm aware of the library functionality, and it's great, but it's not what I need for this.
In theory, I suppose it's very similar, but when doing research I often jump in to my common code and make small changes, save, and jump back to run my notebook, so going through a library would be quite painful.

From the top of your head, do you see a technical issue with mounting another dir in "/Lean/Launcher/bin/Debug/Notebooks"? If not I'll perhaps make a feature request for it, as far as I can tell all the pieces are there already (the docker parameters in the conf.json).
