### ISSUE TITLE
Local libraries are not added to research environment

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [QuantConnect/lean-cli#195]
I've tried following the instructions [here](https://www.quantconnect.com/docs/v2/lean-cli/projects/libraries/project-libraries), but no such luck. The issue started occurring Oct 13, 2022 after updating lean and having downloaded the most recent docker image. FWIW my host OS is Windows 10.

Resulting config.json snippet:

```json
"libraries": [
    {
        "name": "algorithms",
        "path": "Library\\algorithms"
    },
    {
        "name": "indicators",
        "path": "Library\\indicators"
    },
    {
        "name": "nn",
        "path": "Library\\nn"
    },
    {
        "name": "utilities",
        "path": "Library\\utilities"
    }
]
```

**Comment by JakeTheSnake3p0** [comment]
FWIW I compared a new project to my current one and noticed a discrepancy in `.idea/workspace.xml`:

The new project showed `<mapping local-root="$PROJECT_DIR$/../Library" remote-root="/Library" />` whereas my current project showed `<mapping local-root="$PROJECT_DIR$/.." remote-root="/Library" />`.

I tried saving the change but it didn't help the issue. I also added the libraries one by one to the new project and the research.ipynb still fails to recognize any of them.

**Comment by Martin-Molinero** [comment]
Thanks for the report @JakeTheSnake3p0! We are working on it will fix ASAP 👍

**Comment by Martin-Molinero** [comment]
Hey @JakeTheSnake3p0! 
This issue has been fixed by https://github.com/QuantConnect/Lean/pull/6699 please pull the latest lean image and install the latest lean CLI to get the fix.
