### ISSUE TITLE
I can't download Stock Data 

### ISSUE THREAD

**Issue by esabunor** [QuantConnect/lean-cli#20]
Thanks for this awesome library.

I'm encountering an issue when i try to download stock data following the documentation, i get this error. 

Error: Your organization needs to have an active Security Master subscription to download Equity data
You can add the subscription at https://www.quantconnect.com/pricing?organization=<organisation hash>.

**Comment by Martin-Molinero** [comment]
Hey @esabunor!
Please take a look at https://www.quantconnect.com/pricing to download equity data you need and active subscription of ` QuantConnect - Security Master` which will provide stock map and factor files locally

**Comment by esabunor** [comment]
Thanks @Martin-Molinero I’m not sure what exactly QuantConnect - Security Master is and I can’t find a reference to it on the pricing page , but I have an active Quant Researcher subscription. Do I need to upgrade ?

**Comment by jmerle** [comment]
Hi @esabunor,

You can find the Security Master subscription underneath Market Subscriptions -> Datasets Subscriptions on the Pricing page:
![](https://user-images.githubusercontent.com/14951909/124626424-f43fce80-de7e-11eb-9e52-d80b94e1029f.png)

If this section is not visible you may have to click on "Build Your Own Pack" in the top-right corner.

**Comment by esabunor** [comment]
Thanks that answers my question, but on the other hand once I’m subscribed to the Quant Security Master, would I still need QCC to download Eqyity data.
Thanks really appreciate the help

**Comment by jmerle** [comment]
Yes, if you subscribe to the Security Master subscription you are still charged the listed QCC when downloading Equity data.

The Security Master subscription gives you free access to the latest map/factor files of our entire Equity universe for the duration of your subscription. Map files track ticker renaming events, while factor files track split/dividend events. These files are required to run accurate backtests on Equity/Equity Option data, but don't contain the actual Equity/Equity Option price data.

**Comment by esabunor** [comment]
Thanks much appreciated, that answers my questions
