### ISSUE TITLE
stdout -> stdin

### ISSUE THREAD

**Issue by anaderi** [QuantConnect/lean-cli#21]
this line 

https://github.com/QuantConnect/lean-cli/blob/54b77f2554212a279ea0467824e9b98cd9dfbee4/lean/components/util/logger.py#L116

should check stdin instead of stdout.

**Comment by jmerle** [comment]
Good catch, fixed in https://github.com/QuantConnect/lean-cli/commit/ea0a72cb2771b6a33081540473c5aef5e2697cee, released in 1.0.23. Thanks for reporting the issue!
