### ISSUE TITLE
Unable to download Forex data for local backtesting

### ISSUE THREAD

**Issue by adamw96** [QuantConnect/lean-cli#22]
**Expected Behavior**
Documentation [here](https://www.quantconnect.com/docs/v2/lean-cli/user-guides/local-data#03-QuantConnect-Data-Library) suggests Forex data (Oanda) can be downloaded from QC Data Library.

**Actual Behavior**
Fails with error message:
```
Error: There is no data vendor that sells 'forex/oanda/hour/eurusd.zip'
```

**Reproducing**
(Interactive mode)
```
$ lean data download
$ 1
$ 5
$ 4
$ EURUSD
```
(Non-interactive mode)
```
$ lean data download --product "Forex" --organization "MyOrg" --resolution "Hour" --ticker "EURUSD"
```

**System**
Lean CLI 1.0.22

**Comment by jmerle** [comment]
Hi @adamw96,

We pushed some changes to the API to fix this issue. If you re-run the command it should work.

**Comment by adamw96** [comment]
Great, confirmed working v1.0.23
