### ISSUE TITLE
Missing options for `lean data generate`

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#227]
All of [these options](https://github.com/QuantConnect/Lean/blob/60c9162b11327de6b3b71a9b56683a92a10aedc3/ToolBox/Program.cs#L187-L206) should be available to the CLI.

**Comment by DerekMelchin** [comment]
Also, if `--symbol-count` is ingored when we add `--tickers`, then we should be allowed to provide `--tickers` and omit `--symbol-count`.

**Comment by ari62** [comment]
would those options make sense in coordination with the `--data-download` for the `lean backtest `command as well? I am still trying to figure out if `lean backtest` charges me QCC daily for securities I have already downloaded on a previous day, or only when using the --overwrite option, or not at all.

**Comment by ari62** [comment]
it does look like `--download-data` charges daily for each security for each day. So if you ran it yesterday on 2 securities you would pay 200 QCC then if you run it today you would also pay 200 QCC even though it is only 1 more days worth of daily data. Some way to only download data for securities which don't already exist locally via a backtest would be good. I know we can use the `lean data download` and leave off the `--download-data ` argument, but I figure out which securities i need within my backtest.
