### ISSUE TITLE
Error: This is an old Lean CLI root folder

### ISSUE THREAD

**Issue by SusaneK** [QuantConnect/lean-cli#239]
When i run the following code "lean backtest "My Project" -debug" in CMD, it gives the following error:

Error: This is an old Lean CLI root folder.
From now on, a Lean CLI root folder must be created for each organization for improved usability.
For each organization you'd like to use with the CLI, please create a new folder and run `lean init`.

**Comment by Cass0wary** [comment]
Also hitting this issue after upgrading lean `pip install --upgrade lean` from ` version 1.0.97` to `version 1.0.132`

**Comment by Martin-Molinero** [comment]
Hi all!
We've slightly refactored the lean cli folder structure so each init folder is of a single organization, this improves the compatibility with the local vscode extension, sorry for the inconvenience it's caused.
As noted by the error message, you will need to create a new folder and run `lean init` in it.

**Comment by kevinwheeler** [comment]
When I create a directory and then run lean init in it, I get the "Error: This is an old Lean CLI root folder.". I then created a new directory (not in the same directory as the old one) and tried it again. Same thing.

**Comment by Martin-Molinero** [comment]
Hey @melisdirek123! Hard to tell without more details, but I would guess the version of the lean cli your using is old, running with `--verbose` will share much more details to debug this further

**Comment by melisdirek123** [comment]
<img width="509" alt="Image" src="https://github.com/user-attachments/assets/52b42034-51b0-4f2d-80c2-ea835352752f" />
Did I misunderstand the command?

**Comment by melisdirek123** [comment]
Hey @Martin-Molinero ! I wanted to follow up on the above :)
