### ISSUE TITLE
Feature Request: An option to ignore previously downloaded securities when using --download-data

### ISSUE THREAD

**Issue by ari62** [QuantConnect/lean-cli#243]
It looks like `--download-data `charges daily for each security for each day, for daily data in this case, unless you purchase the AlgoSeek Bulk data option. So if you ran it yesterday on 2 securities you would pay 200 QCC then if you run it today you would also pay 200 QCC even though it is only 1 more days worth of daily data. Some way to only download data for securities which don't already exist locally via a backtest would be good. In other words, don't update existing local securities, and only download new securities. I know we can use the `lean data download ` and leave off the `--download-data` argument, but I figure out which securities i need within my backtest.

**Comment by Martin-Molinero** [comment]
Hey @ari62!
Yes, we've recently increased the latency for redownloading data from 1 to 7 days, see https://github.com/QuantConnect/Lean/commit/ce33c393e64051fc445c963ed99e2529c71c88c5, You can adjust the configuration in your `lean.json` config file in the root CLI workspace folder to meet your needs.
Hope that works for you, closing the issue for now
