### ISSUE TITLE
Do Not Restore C# Projects on Pull

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#244]
Since we compile C# projects in the container, we shouldn't restore on the pull, since it would require users to install NET 6.

**Comment by Wilderbill** [comment]
If you are going to reuse the git keywords (push/pull) then you should provide similar behavior
( simply move files back and forth. )

If you have some optional content or behavior, use some new keyword.

    lean cloud download dot-net-addin
