### ISSUE TITLE
Cannot debug using VS 2019

### ISSUE THREAD

**Issue by paultodev** [QuantConnect/lean-cli#25]
I am trying to debug locally using VS 2019.
`C:\LeanCLi> lean backtest "First" --debug vsdbg
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /LeanCLI/First.csproj (in 60 ms).
  First -> /Compile/bin/First.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.30
20210720 11:15:37.878 TRACE:: Config.Get(): Configuration key not found. Key: plugin-directory - Using default value:
20210720 11:15:37.888 TRACE:: Composer(): Loading Assemblies from /Lean/Launcher/bin/Debug
20210720 11:15:37.906 TRACE:: Python for .NET Assembly: QuantConnect.DataSource.ExamplePythonScriptMyCustomDataTypeDoNotUse,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
20210720 11:15:37.950 TRACE:: Python for .NET Assembly: Python.Runtime, Version=2.0.5.0, Culture=neutral,
PublicKeyToken=5000fea6cba702dd
20210720 11:15:37.985 TRACE:: Config.Get(): Configuration key not found. Key: data-directory - Using default value:
../../../Data/
20210720 11:15:37.988 TRACE:: Config.Get(): Configuration key not found. Key: version-id - Using default value:
20210720 11:15:37.989 TRACE:: Config.Get(): Configuration key not found. Key: cache-location - Using default value: /Lean/Data
20210720 11:15:37.990 TRACE:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.5.0.0 Mode: DEBUG (64bit) Host: ROL0003
20210720 11:15:37.994 TRACE:: Engine.Main(): Started 11:15 AM
20210720 11:15:37.997 TRACE:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value:
LocalLeanManager
20210720 11:15:38.014 TRACE:: JobQueue.NextJob(): Selected First.dll
20210720 11:15:38.076 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
20210720 11:15:38.076 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
20210720 11:15:38.077 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
20210720 11:15:38.077 TRACE:: Config.Get(): Configuration key not found. Key: algorithm-id - Using default value: First
20210720 11:15:38.078 TRACE:: Config.Get(): Configuration key not found. Key: job-organization-id - Using default value:
20210720 11:15:38.078 TRACE:: Config.GetValue(): job-project-id - Using default value: 0
20210720 11:15:38.080 TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value:
DataPermissionManager
20210720 11:15:38.091 TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18
TimeInterval: 1440
20210720 11:15:38.093 TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
20210720 11:15:38.105 TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
20210720 11:15:38.371 TRACE:: DebuggerHelper.Initialize(): waiting for debugger to attach...`

But when trying to attach to the docker container process with id 1 I keep receiving:
Initialization log:
Determining user folder on remote system...
Checking for existing installation of debugging tools...
Downloading debugger launcher...
Creating debugger installation folder: /root/.vs-debugger
Copying debugger launcher to /root/.vs-debugger/GetVsDbg.sh
Failed: Failed to copy files.
Unable to find debugger script at '/root/.vs-debugger'.
Failed: Unable to find debugger script at '/root/.vs-debugger'.
The program '[1] dotnet' has exited with code -1 (0xffffffff).

Is this environment issue or it's related to lean?
Thanks.

**Comment by jmerle** [comment]
Hmm, I cannot reproduce this locally using VS 2019. Can you please share the full output `lean backtest "First" --debug vsdbg --verbose` and of `docker info`?

**Comment by paultodev** [comment]
Hi, thanks for looking into this.
Here there are:

` lean backtest "First" --debug vsdbg --verbose
Running 'quantconnect/lean:latest' with the following configuration:
{
    'environment': {'DOTNET_NOLOGO': 'true', 'DOTNET_CLI_TELEMETRY_OPTOUT': 'true'},
    'stop_signal': 'SIGKILL',
    'mounts': [
        {'Target': '/Directory.Build.props', 'Source': 'C:\\Users\\PAULVO~1\\AppData\\Local\\Temp\\lean-cli-177z16oh\\Directory.Build.props', 'Type': 'bind', 'ReadOnly': False},
        {'Target': '/copy_csharp_dependencies.py', 'Source': 'C:\\Users\\PAULVO~1\\AppData\\Local\\Temp\\lean-cli-177z16oh\\copy_csharp_dependencies.py', 'Type': 'bind', 'ReadOnly': False},
        {'Target': '/LeanCLI/First.csproj', 'Source': 'C:\\Users\\PAULVO~1\\AppData\\Local\\Temp\\lean-cli-elepdler\\First.csproj', 'Type': 'bind', 'ReadOnly': True},
        {'Target': '/Lean/Launcher/bin/Debug/config.json', 'Source': 'C:\\Users\\PAULVO~1\\AppData\\Local\\Temp\\lean-cli-isgjbh56\\config.json', 'Type': 'bind', 'ReadOnly': True},
        {'Target': '/lean-cli-start.sh', 'Source': 'C:\\Users\\PAULVO~1\\AppData\\Local\\Temp\\lean-cli-8r_55tq3\\lean-cli-start.sh', 'Type': 'bind', 'ReadOnly': True}
    ],
    'volumes': {
        'C:\\LeanCLi\\data': {'bind': '/Lean/Data', 'mode': 'rw'},
        'C:\\LeanCLi\\First\\backtests\\2021-07-21_10-52-28': {'bind': '/Results', 'mode': 'rw'},
        'C:\\LeanCLi\\First\\storage': {'bind': '/Storage', 'mode': 'rw'},
        'lean_cli_nuget': {'bind': '/root/.nuget/packages', 'mode': 'rw'},
        'C:\\LeanCLi\\First': {'bind': '/LeanCLI', 'mode': 'ro'}
    },
    'ports': {},
    'name': 'lean_cli_vsdbg',
    'entrypoint': ['bash', '/lean-cli-start.sh'],
    'detach': True,
    'hostname': 'ROL0003',
    'tty': True,
    'stdin_open': True,
    'mac_address': 'f8:63:3f:97:8d:b7'
}
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /LeanCLI/First.csproj (in 114 ms).
  First -> /Compile/bin/First.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:14.36
20210721 07:53:11.405 TRACE:: Config.Get(): Configuration key not found. Key: plugin-directory - Using default value:
20210721 07:53:11.420 TRACE:: Composer(): Loading Assemblies from /Lean/Launcher/bin/Debug
20210721 07:53:11.445 TRACE:: Python for .NET Assembly: QuantConnect.DataSource.ExamplePythonScriptMyCustomDataTypeDoNotUse, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
20210721 07:53:11.518 TRACE:: Python for .NET Assembly: Python.Runtime, Version=2.0.5.0, Culture=neutral, PublicKeyToken=5000fea6cba702dd
20210721 07:53:11.584 TRACE:: Config.Get(): Configuration key not found. Key: data-directory - Using default value: ../../../Data/
20210721 07:53:11.594 TRACE:: Config.Get(): Configuration key not found. Key: version-id - Using default value:
20210721 07:53:11.595 TRACE:: Config.Get(): Configuration key not found. Key: cache-location - Using default value: /Lean/Data
20210721 07:53:11.596 TRACE:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.5.0.0 Mode: DEBUG (64bit) Host: ROL0003
20210721 07:53:11.606 TRACE:: Engine.Main(): Started 7:53 AM
20210721 07:53:11.609 TRACE:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
20210721 07:53:11.655 TRACE:: JobQueue.NextJob(): Selected First.dll
20210721 07:53:11.783 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
20210721 07:53:11.784 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
20210721 07:53:11.784 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
20210721 07:53:11.785 TRACE:: Config.Get(): Configuration key not found. Key: algorithm-id - Using default value: First
20210721 07:53:11.787 TRACE:: Config.Get(): Configuration key not found. Key: job-organization-id - Using default value:
20210721 07:53:11.787 TRACE:: Config.GetValue(): job-project-id - Using default value: 0
20210721 07:53:11.788 TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
20210721 07:53:11.813 TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
20210721 07:53:11.818 TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
20210721 07:53:11.838 TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
20210721 07:53:12.737 TRACE:: DebuggerHelper.Initialize(): waiting for debugger to attach...
20210721 07:54:12.778 TRACE:: Isolator.ExecuteWithTimeLimit(): Used: 6, Sample: 6, App: 172, CurrentTimeStepElapsed: 00:00.000`

================
This is docker desktop with WSL2 based engine.
![image](https://user-images.githubusercontent.com/71122101/126453680-f759c339-6186-4462-9415-3ffc4e6b8845.png)

`C:\LeanCLi> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.39GiB
 Name: docker-desktop
 ID: WHRX:3WAU:5LWH:4N5O:DQB7:VKDL:TXAK:IPSO:U2JO:A5RB:ZPTV:KZPT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled`

**Comment by jmerle** [comment]
Sorry for the delay. I cannot reproduce the issue and don't really know what's going on here. Does [debugging in VS Code](https://www.lean.io/docs/lean-cli/tutorials/backtesting/debugging-local-backtests#06-C-and-VS-Code) work correctly? That could be a good alternative for when you need a debugger if Visual Studio doesn't work.
