### ISSUE TITLE
Adds Weekly Restart Time to Interactive Brokers Deployment

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#252]
During the cloud live deployment, the weekly restart parameter is not requested, and the deployment is stop with the following message:
`Error: Weekly restart time is a required parameter.`

**Comment by AlexCatarino** [comment]
I believe the problem has returned because I don't get the option.
I have deleted the configuration key `ib-weekly-restart-utc-time` and it's automatically set to `21:00:00`. I also deleted all IB related keys and it didn't fix the issue.

**Comment by Martin-Molinero** [comment]
Sounds related to https://github.com/QuantConnect/lean-cli/issues/255
