### ISSUE TITLE
No prompt for ib-weekly-restart-utc-time in interactive mode

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#255]
If we deploy a live algorithm with IB in interactive mode (`lean live "MyProj"` / `lean cloud live "MyProj"`), we should be prompted to provide a weekly restart time.

**Comment by Martin-Molinero** [comment]
Closing as duplicate, to be solved by https://github.com/QuantConnect/lean-cli/issues/252
