### ISSUE TITLE
Issue installing LEAN - Help!

### ISSUE THREAD

**Issue by FGLAP** [QuantConnect/lean-cli#263]
Hello,
I am just starting on QuantConnect and am really keen on using it.
Unfortunately, I am struggling to get LEAN installed.
Please see the attached screen shot from the Power Shell.
Your support would be very welcome.
Thanks!

![Screenshot 2023-01-09 225003](https://user-images.githubusercontent.com/122323335/211425974-302f199b-f605-4ea5-9443-fdaff65aab9c.jpg)

**Comment by Martin-Molinero** [comment]
Hi @FGLAP!
Please take a look at our documentation and guides at https://www.quantconnect.com/docs/v2/lean-cli. If you find something is missing/wrong please let us know and we will address it asap
