### ISSUE TITLE
Lean CLI version 1.0.36 is broken when there is a solution file

### ISSUE THREAD

**Issue by omidkrad** [QuantConnect/lean-cli#27]
Hi, after I upgraded Lean CLI to the latest version (1.0.36) I'm having some issues that I could reproduce with the following steps:

1. Create the project under a folder and run backtest. This will work as expected.
```
> lean create-project MyProject/MyAlgo
> lean backtest MyProject/MyAlgo
```

2. On Windows, open the project file in Visual Studio:
```
> devenv ./MyProject/MyAlgo/MyAlgo.csproj
```
Then select "File"->"Save All". It will show the dialog to save the solution file. Save the solution file as: `MyProject/MyProject.sln`

3. Backtest will fail now.
```
> lean backtest MyProject/MyAlgo

Error: 500 Server Error for
http+docker://localnpipe/v1.41/containers/2b1e943a08d2c169ff9731c202eaeab03e40fe8a7759d3641002ecfd6786185f/start:
Internal Server Error ("OCI runtime create failed: container_linux.go:380: starting container process caused:
process_linux.go:545: container init caused: rootfs_linux.go:76: mounting
"/run/desktop/mnt/host/c/Users/dvp/AppData/Local/Temp/lean-cli-2e8ke7tc/MyAlgo/MyAlgo.csproj" to rootfs at
"/LeanCLI/MyAlgo\\MyAlgo.csproj" caused: open /var/lib/docker/overlay2/6f125dc13c510204bf0181082b735079b0445f61185984f48
ea9e7e360e87eb5/merged/LeanCLI/MyAlgo\MyAlgo.csproj: read-only file system: unknown")
```

4. Remove the solution file we just created.
```
> rm ./MyProject/MyProject.sln
```

5. Run backtest again. It will run again with no error.
```
> lean backtest MyProject/MyAlgo
```

**Comment by jmerle** [comment]
Fixed in https://github.com/QuantConnect/lean-cli/commit/ce3692c3168389f1a0039a702f27b06fd1af8340, released in 1.0.37, thanks for reporting the issue!
