### ISSUE TITLE
C# Cloud Libraries

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#277]
Lean-CLI should provide the C# libraries available in QuantConnect Cloud.
We document the following list: [get-libraries.py#L24:L79](https://github.com/QuantConnect/Documentation/blob/master/code-generators/get-libraries.py#L24:L79) which users need to manually add to a custom Lean build.

**Comment by Martin-Molinero** [comment]
This behavior can be achieved using `lean library add` 
```
> lean library add TestProject "Microsoft.ML"
Adding package Microsoft.ML to project D:\quantconnectOrg\TestProject
Retrieving latest available version from NuGet
Adding Microsoft.ML 2.0.1 to 'TestProject\TestProject.csproj'
Restoring packages in 'TestProject' to provide local autocomplete
Restored successfully
```
