### ISSUE TITLE
Error: attributes construct error

### ISSUE THREAD

**Issue by pieroliviermarquis** [QuantConnect/lean-cli#283]
I get this error when creating a new project.

```
lean project-create --language python "My Python Project"
Error: attributes construct error, line 11, column 42 (<string>, line 11)
```

lean, version 1.0.141
Python 3.9.16
Windows 10 Home 64-bit 10.0

**Comment by Martin-Molinero** [comment]
Hey @pieroliviermarquis!
Sorry for the delay here. Is this still an issue for you? mind adding `--verbose` and sharing the logs

**Comment by Martin-Molinero** [comment]
Closing for now, please feel free to reopen if you can reproduce, please share the projects content & the output of `>lean --version --verbose`, thank you!
