### ISSUE TITLE
lean research /LeanCLI is not mounted, skipping compilation...

### ISSUE THREAD

**Issue by JanUdo** [QuantConnect/lean-cli#291]
Help appreciated - any ideas? jupyter is starting but I am not able use the Lean liberaries: "NameError: name 'QuantBook' is not defined. "  The other LeanCli commands are working

(base) C:\Users\QCWorkspace>lean research "p1" --verbose
Context information:
  Python version: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
  OS: Windows-10-10.0.22621-SP0
  Lean CLI version: 1.0.144
C:\Users\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Running 'quantconnect/research:latest' with the following configuration:
{
    'environment': {},
    'stop_signal': 'SIGKILL',
    'mounts': [
        {
            'Target': '/Lean/Launcher/bin/Debug/config.json',
            'Source': 'C:\\Users\\AppData\\Local\\Temp\\lean-cli-w_laa0zw\\config.json',
            'Type': 'bind',
            'ReadOnly': True
        },
        {
            'Target': '/Lean/Launcher/bin/Debug/Notebooks/config.json',
            'Source': 'C:\\Users\\AppData\\Local\\Temp\\lean-cli-w_laa0zw\\config.json',
            'Type': 'bind',
            'ReadOnly': True
        },
        {
            'Target': '/lean-cli-start.sh',
            'Source': 'C:\\Users\\AppData\\Local\\Temp\\lean-cli-5767o3aq\\lean-cli-start.sh',
            'Type': 'bind',
            'ReadOnly': True
        }
    ],
    'volumes': {
        'C:\\Users\\QCWorkspace\\p1': {'bind': '/Lean/Launcher/bin/Debug/Notebooks', 'mode': 'rw'},
        'C:\\Users\\QCWorkspace\\data': {'bind': '/Lean/Data', 'mode': 'rw'},
        'C:\\Users\\AppData\\Local\\Temp\\lean-cli-ge8orxsh': {'bind': '/Results', 'mode': 'rw'},
        'C:\\Users\\QCWorkspace\\p1\\storage': {'bind': '/Storage', 'mode': 'rw'}
    },
    'ports': {'8888': '8888'},
    'name': 'lean_cli_01c81cd104cd4c70b54a8e86b44971b3',
    'entrypoint': ['bash', '/lean-cli-start.sh'],
    'detach': True,
    'hostname': 'Yoga',
    'tty': True,
    'stdin_open': True,
    'network': 'lean_cli'
}
+ '[' -d /LeanCLI ']'
+ echo '/LeanCLI is not mounted, skipping compilation...'
/LeanCLI is not mounted, skipping compilation...
+ mkdir -p /root/.jupyter
+ echo 'c.ServerApp.disable_check_xsrf = True
c.ServerApp.tornado_settings = {'\''headers'\'': {'\''Content-Security-Policy'\'': '\''frame-ancestors self *'\''}}'
+ mkdir -p /root/.ipython/profile_default/static/custom
+ echo '#header-container { display: none !important; }'
+ ./start.sh
....

**Comment by Martin-Molinero** [comment]
Hey @JanUdo!
Suggest running `docker pull quantconnect/research` to get the latest lean version and making sure the right kernel is selected. Is `p1` a `python` project? At the moment C# kernels have a dotnet bug reported see https://github.com/QuantConnect/Lean/issues/6710.
![image](https://user-images.githubusercontent.com/18473240/222850556-61047c0d-d8c0-45d0-8b8a-5c4c45dfb4c5.png)

**Comment by JanUdo** [comment]
Thank you for the fast reply! I fixed the problem by selecting the right kernel - easy :-)
