### ISSUE TITLE
lean cloud backtest push error

### ISSUE THREAD

**Issue by angusscli** [QuantConnect/lean-cli#305]
I can no longer push backtest to cloud, error as below:

`D:\Project\BackTesting> lean cloud backtest "Test" --push          
[1/1] Pushing 'Test'
Cannot push 'Test': 1 validation error for QCProject
liveResults
  none is not an allowed value (type=type_error.none.not_allowed)
Error: 1 validation error for QCProject
liveResults
  none is not an allowed value (type=type_error.none.not_allowed)`

**Comment by Martin-Molinero** [comment]
Thanks for the report @angusscli!
