### ISSUE TITLE
How can I go to debug mode for Python?

### ISSUE THREAD

**Issue by avatarstones** [QuantConnect/lean-cli#321]
Don't want to buy Pycharm pro.
Simply want to use pdb set_trace do debug.
Could you please let me know how can I turn on pdb set_trace?
Thanks.

When I tried
lean backtest "xxx" --debug local-platform
got error:
Error: Invalid value for '--debug': 'local-platform' is not one of 'pycharm', 'ptvsd', 'vsdbg', 'rider'.

**Comment by Martin-Molinero** [comment]
Hey @avatarstones!
Please visit https://www.quantconnect.com/docs/v2/lean-cli/backtesting/debugging for steps for local debugging
