### ISSUE TITLE
Is Windows Server Datacenter 2019 supported?

### ISSUE THREAD

**Issue by wayneadams** [QuantConnect/lean-cli#33]
Hi there,

Is Windows Server Datacenter 2019 supported?

I'm attempting to run `lean research` and `lean backtest`. But lean is failing to pull both the quantconnect/research and quantconnect/lean images. 

When I run `lean research .` in a project's directory, I'm getting the output below:

```
PS C:\Users\wadams19\workspace\QC\live\coin-toss> lean research .
Pulling quantconnect/research:latest...
latest: Pulling from quantconnect/research
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries
Error: Something went wrong while pulling quantconnect/research:latest, see the logs above for more information
```

Any ideas?

**Comment by Martin-Molinero** [comment]
Hey! Sorry for the late response but it sounds like a docker bug/limitation, suggest retesting with the latest docker desktop for windows it's come a long way since then, support has improved significantly 👍
