### ISSUE TITLE
Feature request: GPU support

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/lean-cli#36]
With reference to [this community post](https://www.quantconnect.com/forum/discussion/12449/add-gpu-in-learn-locally/p1)

Since GPUs in local machines are not utilized in LEAN CLI, the support for extra computational power by GPUs for machine learning in the research environment is requested.

**Comment by otreewen2020** [comment]
it is NOT a problem now. please refer to: https://www.quantconnect.com/forum/discussion/12449/add-gpu-in-learn-locally/p1

**Comment by jaredbroad** [comment]
Thanks for sharing @otreewen2020! Nice work!
