### ISSUE TITLE
`lean init` not adding `organization-id` when creating lean.json

### ISSUE THREAD

**Issue by rjra2611** [QuantConnect/lean-cli#369]
- Not able to reproduce the issue on my machine. Attaching screenshots provided by user

![image](https://github.com/QuantConnect/lean-cli/assets/28739120/1bf8b47e-663f-4787-a06e-7c9bca14054f)

![image](https://github.com/QuantConnect/lean-cli/assets/28739120/0fe2ca23-55b8-404b-af7a-ca3f1bcc805b)

![image](https://github.com/QuantConnect/lean-cli/assets/28739120/44747091-723b-421a-b6d8-0963f6a9e90f)

**Comment by Martin-Molinero** [comment]
Lot's has changes since this, we haven't seen this again, closing until we get recent reports
