### ISSUE TITLE
Encrypted Projects with Collaborators

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#381]
In [Cloud Platform](https://www.quantconnect.com/docs/v2/cloud-platform/projects/encryption#07-Collaboration-Support) docs, we say
> Encryption isn’t available for projects that have [collaborators](https://www.quantconnect.com/docs/v2/cloud-platform/projects/collaboration).

but we can get around it with the cli

1. Create a new project in QC Cloud
2. Add a collaborator
3. Run these commands
```
D:\qc\workspaces\quantconnect>lean cloud pull --project "Encryption Collab Test"
[1/1] Pulling 'Encryption Collab Test'
Successfully pulled 'Encryption Collab Test/main.py'
Successfully pulled 'Encryption Collab Test/research.ipynb'

D:\qc\workspaces\quantconnect>lean cloud push --project "Encryption Collab Test" --encrypt --key "C:\Users\derek\Desktop\encryption-file.txt"
[1/1] Pushing 'Encryption Collab Test'
Successfully updated name, files, libraries, and encryption_key for 'Encryption Collab Test'
```

**Comment by rjra2611** [comment]
Collaboration check added in the API side
