### ISSUE TITLE
Pushing Files to Cloud with Invalid Names Logs Wrong Information

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#39]
When we push a file to cloud with invalid name, the message is not correct:
Create new project named ShortFileTest in QuantConnect.com, and pull it:
`$ lean cloud pull --project "ShortFileTest"`
add lib.py file to the ShortFileTest directory and push the project
`$ lean cloud push --project "ShortFileTest"`

The following message is shown:
_"Cannot push 'ShortFileTest 2' (failed on $HOME\Local\ShortFileTest\lib.py): Invalid credentials, please log
in using `lean login`"_
where it should inform that the file name is too short.

**Comment by antb88** [comment]
Could you clarify what would be an invalid name? I seem to be hitting on this issue with `tmp.py`:
```
Cannot push 'QC' (failed on /somepath/tmp.py): Invalid credentials, please log in using `lean login`
```

**Comment by rjra2611** [comment]
Looks fixed when trying to reproduce with short file name `a.py` 

![image](https://user-images.githubusercontent.com/28739120/171938881-d8172af5-6b87-44b3-8a4c-3f3b11bc2551.png)
