### ISSUE TITLE
IB 2FA Prompt

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#390]
This output
> To use IB with LEAN you must disable two-factor authentication or only use IBKR Mobile. This is done from your IB
Account Manage Account -> Settings -> User Settings -> Security -> Secure Login System. In the Secure Login System,
deselect all options or only select "IB Key Security via IBKR Mobile". Interactive Brokers Lite accounts do not support
API trading.

should be updated to match the deployment wizard in QC Cloud

>To use IB with QuantConnect you must use IBKR Mobile. This is done from your IB Account Manage Account -> Settings -> User Settings -> Security -> Secure Login System. In the Secure Login System, select "IB Key Security via IBKR Mobile". Your account details are not saved on QuantConnect. Interactive Brokers Lite accounts do not support API trading.

**Comment by Priyal-Saxena** [comment]
Hey, I can't seem to find this prompt in lean-cli repository. Is it present somewhere else?

**Comment by Martin-Molinero** [comment]
Solved in latest version 👍
