### ISSUE TITLE
`lean data download` start and end dates

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#392]
The interactive mode asks for start and end dates, but the non-interactive mode doesn't accept them as options.

![image](https://github.com/QuantConnect/lean-cli/assets/38889814/8340c9bb-5a3e-4514-9cb0-034509def2d3)

**Comment by Martin-Molinero** [comment]
This issue has been fixed in latest lean CLI version 1.0.195 👍
