### ISSUE TITLE
Extra data: line 1 column 21977 (char 21976) - REOPENED

### ISSUE THREAD

**Issue by alphaDev23** [QuantConnect/lean-cli#398]
Issue was entered yesterday but then prematurely closed.

Upgrade lean to 1.0.177 and I now receive the following error regardless of the lean command , including using --verbose.  I run. E.g.,

lean whoami --verbose
Extra data: line 1 column 21977 (char 21976)
Extra data: line 1 column 21977 (char 21976)
<string>:595 Unexpected """ at column 1
Extra data: line 1 column 21977 (char 21976)
Error: <string>:595 Unexpected """ at column 1

Please advise as to which file this error may be coming from and how to fix. As a note, prior versions, down to 1.0.170 also now exhibit the same errors. The issue was not there prior to the upgrade.

Same issue yesterday and today.

**Comment by Martin-Molinero** [comment]
Hey @alphaDev23
Can you please run the command with --verbose and share the output?

**Comment by alphaDev23** [comment]
Running the command with --verbose is in the original post.  I will try the suggestion in your edit by this weekend.

**Comment by Martin-Molinero** [comment]
> Running the command with --verbose is in the original post. I will try the suggestion in your edit by this weekend.

Thank you @alphaDev23. Please keep us posted if, and how, ur able to solve the issue. Curious if your using the vscode local platform QC extension too? Trying to determine what could of caused the corruption

**Comment by alphaDev23** [comment]
The lean.json file appears to have been corrupted.  I ran `lean init` in another folder, copied the lean.json file to the other folder and it ran without exception.
