### ISSUE TITLE
Weird Output On Completion Of `lean data download`

### ISSUE THREAD

**Issue by rjra2611** [QuantConnect/lean-cli#407]
Command Used

`lean data download --dataset "US Equities"  --data-type "Bulk" --resolution "Daily"  --start "20230101" --end "20231231"`

![image](https://github.com/QuantConnect/lean-cli/assets/28739120/41bee9ad-f9ad-4e88-8392-d30580c8ee95)

**Comment by jaredbroad** [comment]
IMHO That is likely dumping the zip contents to the screen due to invalid use of reserved file name con.csv

**Comment by Martin-Molinero** [comment]
Downloaded twice and can't reproduce this issue, could of been some download corruption maybe, can u reproduce @rjra2611? Maybe we could validate the file before trying to unzip

**Comment by rjra2611** [comment]
> Downloaded twice and can't reproduce this issue, could of been some download corruption maybe, can u reproduce @rjra2611? Maybe we could validate the file before trying to unzip

Tried with `lean 1.0.202` -- LGTM

![image](https://github.com/user-attachments/assets/a695f33f-835c-4af3-9fb9-ef49385f966e)
