### ISSUE TITLE
Review Python Requirements

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#421]
We build Lean CLI for Python versions 3.7 to 3.10
https://github.com/QuantConnect/lean-cli/blob/master/.github/workflows/build.yml#L12
However, `quantconnect-stubs` depends on `pandas>=1.5.3`, and pandas 1.5 doesn't support Python 3.8.
https://pandas.pydata.org/pandas-docs/version/1.5/getting_started/install.html

Users with Python 3.7 can't install recent versions of Lean CLI:

```
ERROR: Cannot install lean because these package versions have conflicting dependencies.

The conflict is caused by:
quantconnect-stubs 16243 depends on pandas>=1.5.3
```

**Comment by Martin-Molinero** [comment]
`quantconnect-stubs` will no longer enforce a pandas or matplotlib version, see https://github.com/QuantConnect/quantconnect-stubs-generator/pull/18
