### ISSUE TITLE
Lean CLI skips input for brokerage api key & secret

### ISSUE THREAD

**Issue by symbion6** [QuantConnect/lean-cli#426]
#### Expected Behavior
When executing 'lean live', the CLI asks for the brokerage's API Key & Secret, after selecting a brokerage & data provider from the menu.

#### Actual Behavior
When executing 'lean live', the CLI does NOT ask for the brokerage's API Key & Secret, after selecting a brokerage & data provider from the menu.

The consequence is that the connection to the exchange cannot be made and Lean exits with an error.

#### Potential Solution
Ask for the brokerage's API Key & Secret after selecting brokerage & data provider.

#### Reproducing the Problem 
* Do a clean install of the lean CLI.
* Use 'lean live <projectname>' to start a project.
* Select either Kraken or Bybit from the brokerage menu (not sure if it also skips for other exchanges)
It will now show 

> Configure credentials for Kraken
> Create an API key by logging in and accessing the Kraken API Management page (https://www.kraken.com/u/security/api).

....but will not actually give a prompt to input the key & secret, as it did before and should do.

#### System Information
Ubuntu 22.04 TLS

#### Checklist
- [V] I have completely filled out this template
- [V] I have confirmed that this issue exists on the current `master` branch
- [V] I have confirmed that this is not a duplicate issue by searching git repo
- [V] I have provided detailed steps to reproduce the issue

#### Log

[lean_cli_log_excerpt_24022024.log](https://github.com/QuantConnect/lean-cli/files/14394398/lean_cli_log_excerpt_24022024.log)

**Comment by symbion6** [comment]
Please close as this turns out to be a Lean Engine issue, not a CLI issue.

**Comment by Martin-Molinero** [comment]
Hey @symbion6! Thank you for the report, we will look into it, this is a lean-cli issue 👍. FYI we are currently working on a lean CLI refactor handling modules and configurations, so we will fix this issue at it

**Comment by symbion6** [comment]
Anything that can help us getting our bot back online would be great. We cannot start it at the moment :-(

**Comment by Martin-Molinero** [comment]
Hey @symbion6! 
> The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters

Seen this issue in kraken when using invalid keys, suggest double checking ur providing the correct key and secret, secret is the long one.

> Error getting cash balance from
brokerage

Would nee to see the entire log but this also seems like invalid key/secret configuration for bybit too

**Comment by Martin-Molinero** [comment]
Closing for now, believe there's no issue, please reopen if it's still happening and provide more details so we can fix it asap 👍
