### ISSUE TITLE
Not able to specify multiple data providers with the cloud live deploy command

### ISSUE THREAD

**Issue by lifelonginvestor** [QuantConnect/lean-cli#432]
It was working before with the param ib-data-feed. I can set a list of data providers with comma as delimiter. The new param --data-provider-live won't work now. please fix if possible.

Usage: lean cloud live deploy [OPTIONS] PROJECT

Try 'lean cloud live deploy --help' for help or go to the following url for a list of common errors:
https://www.lean.io/docs/v2/lean-cli/key-concepts/troubleshooting#02-Common-Errors

Error: Invalid value for '--data-provider-live': 'QuantConnect,Interactive Brokers' is not one of 'QuantConnect', 'Interactive Brokers', 'Tradier', 
'Oanda', 'Bitfinex', 'Coinbase Advanced Trade', 'Binance', 'Zerodha', 'Samco', 'Terminal Link', 'Trading Technologies', 'Kraken', 'TDAmeritrade', 
'Polygon', 'IEX', 'CoinApi', 'Bybit'.

**Comment by Martin-Molinero** [comment]
Hey @lifelonginvestor! The error is showing you the new possible expected values, before we only allowed very specific combinations, now it's generic.

**Comment by codebycase** [comment]
@Martin-Molinero How do I specify multiple providers then? This is not working for me as I was trying to split them with comma. What's the correct way to specify multiple providers.

'--data-provider-live': 'QuantConnect,Interactive Brokers'

**Comment by Martin-Molinero** [comment]
For example `lean cloud live deploy 17354101 --data-provider-live QuantConnect --data-provider-live "interactive brokers"`

**Comment by codebycase** [comment]
Thanks! it works.
