### ISSUE TITLE
New update broke CryptoCoarseFundamentalUniverse

### ISSUE THREAD

**Issue by GitHubUser97** [QuantConnect/lean-cli#434]
As in the title, lean cli forced an update on itself, then  CryptoCoarseFundamentalUniverse stopped working. 
I get  name 'CryptoCoarseFundamentalUniverse' is not defined now.

**Comment by jaredbroad** [comment]
Addressed here (https://github.com/QuantConnect/Lean.DataSource.CryptoCoarseFundamentalUniverse/pull/13)

ETA 30min.

**Comment by GitHubUser97** [comment]
Thank you Jared.
I've got an answer on discord. For anyone else encountering, I attach an example implementation vs old one.
Also a working example by quantconnect team: https://github.com/QuantConnect/Lean.DataSource.CryptoCoarseFundamentalUniverse/blob/master/CryptoCoarseFundamentalUniverseSelectionAlgorithm.py

old:
```
uniSettings = UniverseSettings(Resolution.Hour, 1, True, False, timedelta(days=0))
        self.AddUniverse(CryptoCoarseFundamentalUniverse(Market.Binance, uniSettings, self.CoarseSelectionFunction))
``` 

new:
```         
uniSettings = UniverseSettings(Resolution.Hour, 1, True, False, timedelta(days=0))
self.UniverseSettings = uniSettings
    
 self.AddUniverse(CryptoUniverse.Binance(self.CoarseSelectionFunction) ) ```
