### ISSUE TITLE
Error: 1 validation error for QCProject liveResults field required

### ISSUE THREAD

**Issue by RyanRTJJ** [QuantConnect/lean-cli#435]
Hi team, I've been using lean for quite some time now with no problem, but now, after 2 weeks of not using it, and trying to do `lean cloud backtest "Sample" --push --open` as per normal (where "Sample" is the name of my strategy dir), I suddenly get this error:
```
Error: 1 validation error for QCProject
liveResults
  field required (type=value_error.missing)
```
I know that the field `liveResults` is missing from my config, but:
- where is my config file that I can change (what should I change it to)
- more importantly, why did this just suddenly happen? I did not change anything, and I even reinstalled lean.

Thank you!

**Comment by Martin-Molinero** [comment]
Hey @RyanRTJJ! The field was removed some time ago already https://github.com/QuantConnect/lean-cli/pull/306/files. Please update your lean cli to the latest version to solve this issue `pip install --upgrade lean` 👍. 
If the issue persists please report back running the command with `--verbose` and sharing the complete output so we can debug it better
