### ISSUE TITLE
Backtest Internal Error: No space left on device

### ISSUE THREAD

**Issue by codebycase** [QuantConnect/lean-cli#436]
An error occurred during this backtest:
[ERROR] FATAL UNHANDLED EXCEPTION:JobQueueCloud.GetAlgorithmJob(BACKTESTING-114-b6805fb78a26829fdcfb80653bbda992): Internal Error: No space left on device
: '/QuantConnect/backtesting/cache',Engine.Main(): Sorry we could not process this algorithm request.,Unhandled exception. System.ArgumentException: 
Engine.Main(): Sorry we could not process this algorithm request.,   at QuantConnect.Lean.Launcher.Program.Main(String[] args) in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/LeanEnterprise/Launcher/Program.cs:line 75,runLauncher.sh: line 17:     7 Aborted                 (core 
dumped) dotnet QuantConnect.Lean.Launcher.dll --data-folder /Data --config /QuantConnect/backtesting/airlock/config.json --results-destination-folder 
/QuantConnect/backtesting/airlock/

**Comment by AlexCatarino** [comment]
Please contact support@quantconnect.com for QuantConnect Cloud issues.
