### ISSUE TITLE
Error: 4 validation errors for QCProject

### ISSUE THREAD

**Issue by lifelonginvestor** [QuantConnect/lean-cli#440]
Got following error with backtest today, please investigate and fix:

lean cloud backtest liats
Error: 4 validation errors for QCProject
collaborators -> 0 -> id
  field required (type=value_error.missing)
collaborators -> 0 -> blivecontrol
  field required (type=value_error.missing)
collaborators -> 0 -> epermission
  field required (type=value_error.missing)
collaborators -> 0 -> profileimage
  field required (type=value_error.missing)

**Comment by Martin-Molinero** [comment]
Hey @lifelonginvestor! Please your lean cli version to the latest, we pushed a fix for this yesterday, see https://github.com/QuantConnect/lean-cli/releases/tag/1.0.186
