### ISSUE TITLE
QuantConnect Web UI fails to open any backtest results at this point

### ISSUE THREAD

**Issue by lifelonginvestor** [QuantConnect/lean-cli#458]
QuantConnect Web UI fails to open any backtest results at this point. Should be something broken under the hood, please investigate and fix. thanks.

**Comment by Martin-Molinero** [comment]
Hey @lifelonginvestor! Sorry for the inconvenience, please contact support with more details on how to reproduce your issue so we can fix it ASAP

**Comment by Martin-Molinero** [comment]
Believe this issue has been fixed, please re open with more details or contact support if it's still happening for you
