### ISSUE TITLE
--verbose adds extra context information

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/lean-cli#459]
- dotnet version, if installed/available
- code version (vscode), if installed/available
    - we can even see the installed extensions `--list-extensions` and ideally their versions too
- the foundation image labels in the images being used, if available see https://github.com/QuantConnect/Lean/commit/529841ea776a7c3c3d04ca740be4e34b660ae087 . Lean CLI already reads label from images, see https://github.com/QuantConnect/lean-cli/pull/441, reuse. Research image & lean engine image

See related https://github.com/QuantConnect/Lean/issues/8015

See https://github.com/QuantConnect/lean-cli/blob/master/lean/click.py#L51

**Comment by jaredbroad** [comment]
@Marinovsky

**Comment by Martin-Molinero** [comment]
Reopening so we add user name running the command, docker version, see related https://github.com/QuantConnect/lean-cli/issues/515
