### ISSUE TITLE
Invalid argument for `lean cloud status`

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#468]
I created a project on QC Cloud and deploy it, then I pulled the project from QC Cloud (so it has a projected).

I get Error: Invalid argument
```
GET https://www.quantconnect.com/api/v2/live/read with data:
{
    "start": 86400,
    "end": 1718889068
}
```

the parameters are incorrect or the endpoint. The endpoint should probably be `/live/list`, because if I replace it I get the correct results:

```
Project id: 18370084
Project name: Pensive Black Sheep
Project url: https://www.quantconnect.com/project/18370084
Live status: Running
Live id: L-027e845c413982f26ce492ce7021d5dd
Live url: https://www.quantconnect.com/project/18370084/live
Brokerage: PaperBrokerage
Launched: 2024-06-20 13:01:21 UTC
```

**Comment by Martin-Molinero** [comment]
Fixed by https://github.com/QuantConnect/lean-cli/pull/476
