### ISSUE TITLE
Feature Request: Stop a running live cloud algorithm from the CLI

### ISSUE THREAD

**Issue by InvestWeMust** [QuantConnect/lean-cli#47]
Hello, I would like to build an automated process to restart my live algorithm from the CLI weekly to make sure that I am running the most up-to-date version of LEAN.  

Starting the algorithm from the CLI is not a problem, however, there is currently no way to stop a running algorithm, or even to force restart the algorithm.  If a live node is in use, the only thing that works is to manually go in to the GUI and stop the algorithm running on it.  Only then is the node available to deploy to from the CLI.

Is it possible to get this capability as a either a separate CLI API, or even as a "force" parameter to the `lean cloud live` API?

**Comment by jaredbroad** [comment]
Cool idea @InvestWeMust thank you, we'll try and get it built. 

We're pushing a few heavy projects at the moment so it'll be closer to January unfortunately, or if anyone feels like contributing the code it's all well defined in the REST API.

**Comment by InvestWeMust** [comment]
Hey @jaredbroad, I ended up having some free time and implemented this functionality in the CLI. I created a pull request for it here: https://github.com/QuantConnect/lean-cli/pull/53

I'd love for someone from your team to take a look at it and provide feedback.  Please let me know if there are any other processes or documentation that I need to follow/update.

**Comment by Martin-Molinero** [comment]
Closed by https://github.com/QuantConnect/lean-cli/pull/123
