### ISSUE TITLE
NO UPDATE Command Enforces Updates

### ISSUE THREAD

**Issue by zurpet** [QuantConnect/lean-cli#479]
Despite using `--no-update` command, lean cli enforces updates of certain packages (ie. brokerage packages). This behaviour is not desirable because any update could potentionally introduce a new bug.

Here is an example of this behaviour:
![no-update-flag-image](https://github.com/user-attachments/assets/4f9a7948-6142-44c8-901e-dc6e04cec9ce)

**Comment by Martin-Molinero** [comment]
If `--no-update` is given, using int `lean_version` label inside of the lean images we fetch the modules which versions are <= to it, instead of latest
