### ISSUE TITLE
Backtest fails after building project with both Debug and Release configurations

### ISSUE THREAD

**Issue by omidkrad** [QuantConnect/lean-cli#48]
Steps to reproduce:

```bash
lean create-project my-project
dotnet build my-project # --configuration Debug
dotnet build my-project --configuration Release
lean backtest my-project
```

Backtest will fail with this error:
```console
/LeanCLI/lean-cloud/my-project/obj/Release/.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate
'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [/LeanCLI/lean-cloud/my-project/my-project.csproj]
.
.
.
```

I noticed the project will run again after deleting the `obj` directory.

```bash
rm -r my-project/obj
```

I think to fix it, we can get `lean` command to remove the `obj` directory before running backtest, or maybe we could use the `.dockerignore` file to exclude the build artifacts from going into the docker image.

**Comment by Martin-Molinero** [comment]
Hey @omidkrad !
There is no need to manually build the project this is probably causing the issues, `lean` will build the project automatically. The following are working out of the box with current master:
> `lean create-project test`
> `lean backtest test`
I'll close the issue but please re open and provide logs if this is not the case for you 👍
