### ISSUE TITLE
"lean encrypt" does not work with Chinese comment

### ISSUE THREAD

**Issue by pizikuan** [QuantConnect/lean-cli#493]
lean encrypt xxxxx --key "D:\Backup\quantconnect_encryt.txt"                     

Error: Could not encrypt project D:\Work\QuantConnect\xstrategy: Failed to encrypt file 
D:\Work\QuantConnect\xxxxx\base.py with error 'gbk' codec can't decode byte 0xa1 in position 523: illegal    
multibyte sequence

lean encrypt does not work with Chinese comment. "position 523" is the first Chinese character in this file with UTF8 encoding.

**Comment by Marinovsky** [comment]
Hey @pizikuan !

Could you please share a file with the portion of `base.py` that has the characters producing this exception? So far we've been able to reproduce a similar but not the same exception, namely:  `charmap' codec can't decode byte 0x8d in position 78: character maps to <undefined>`. It would be also useful if you could share with us the logs when you run that same command with `--verbose`

**Comment by pizikuan** [comment]
import json
import logging
import sys

class MyConfig:
    DEBUG = True  # 调试模式，会打印出更多的log

**Comment by Marinovsky** [comment]
Hey @pizikuan !

I tested in my local (using the latest version of lean-cli) the encrypt command with a file containing that portion of code you provided and it worked (both encrypt and decrypt, using both UTF-8 and GB2312 encodings). Could you please retry encrypting the project that was failing using the latest version of lean-cli?

**Comment by pizikuan** [comment]
It works，thank you.在 2024年9月9日，22:00，Ricardo Andrés Marino Rojas ***@***.***> 写道：﻿
Hey @pizikuan !
I tested in my local (using the latest version of lean-cli) the encrypt command with a file containing that portion of code you provided and it worked (both encrypt and decrypt, using both UTF-8 and GB2312 encodings). Could you please retry encrypting the project that was failing using the latest version of lean-cli?
