### ISSUE TITLE
The Cloud backtest throws the errors some times.

### ISSUE THREAD

**Issue by investorlifelong** [QuantConnect/lean-cli#521]
An error occurred during this backtest:
[ERROR] FATAL UNHANDLED EXCEPTION:Unable to find image 'quantconnect/backtesting:16772' locally,docker: Error response from daemon: pull access denied for
quantconnect/backtesting, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.,See 'docker run 
--help'.

**Comment by Martin-Molinero** [comment]
Thank you for the report, we will fix this asap
