### ISSUE TITLE
Security Master check is hardcoded and non-specific

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/lean-cli#73]
Currently the system of checking for "Security Master" subscription only considers "Equity Security Master". However, different datasource require different "Security Master" products.

In example:
Bulk US Equity Data -> Bulk US Equity Security Master (PID 180)
US Equity Data -> US Equity Security Master (PID 37)
Bulk US Futures Data -> Bulk US Futures Security Master (PID 179)
US Futures Data -> US Futures Security Master (PID 137)

I believe this can be addressed by a two step change. One to the API and then the CLI reflecting.

SOLUTION:

The web api response for "data/prices" under "datasources" has a field "requiresSecurityMaster" which is a simple true/false. Instead I suggest we make this a `requires` field as an int[] that contains the required products if any for that Product id. 

EX Before
```
	"datasources": {
		"4": {
			"requiresSecurityMaster": true,
			"options": [],
			"paths": []
		}
        }
```

EX after
```
	"datasources": {
		"4": {
			"requires": [ 37 ],
			"options": [],
			"paths": []
		}
        }
```

That way in the CLI when we want to check if a product can be downloaded we can just ensure that the required product ID exists in the organization subscriptions. 

This also allows us to not have to hardcode any security master product ID in the CLI as it is now.

**Comment by jaredbroad** [comment]
Fixed 2022
