### ISSUE TITLE
Local Data Feed Options Aren't Correct

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#78]
If I deploy a local live algorithm to Coinbase Pro with the CLI, the prompts ask me to select either the Coinbase Pro or IQFeed data feed. 
The following IQFeed docs don't show Crypto as a supported asset class:
- https://ws1.dtn.com/IQ/Search/
- https://iqfeed.net/symbolguide/

**Comment by Martin-Molinero** [comment]
This is a grey area, current implementation is generic and allows cross asset data requests connecting to multiple data feeds at the same time. You can even argue it's a feature potentially enabling some arbitrage opportunities
