### ISSUE TITLE
Account tiers don't display when deploying cloud algorithms

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#80]
If we deploy a local algorithm with the CLI or a cloud algorithm from quantconnect.com that uses the FTX brokerage, the account tiers display.
![image](https://user-images.githubusercontent.com/38889814/159057369-b7420245-9b8e-4bf8-9f2e-75cd662f20ec.png)
![image](https://user-images.githubusercontent.com/38889814/159057094-2f80eae5-666c-4446-b763-57ea230e72bd.png)

However, if we deploy a cloud algorithm with the CLI, the account tiers don't display 

![image](https://user-images.githubusercontent.com/38889814/159057502-fb6c00d6-e3b9-4b80-af6b-4552b0bc8b96.png)

We have the same issue with verification tiers when deploying with the Kraken brokerage.

**Comment by Martin-Molinero** [comment]
Solved by https://github.com/QuantConnect/lean-cli/pull/91
