### ISSUE TITLE
The hybrid QC-IB data feed isn't supported

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#81]
When you run `lean cloud live` with the `--brokerage "Interactive Brokers"` option, the `--ib-data-feed` option [is a boolean](https://github.com/QuantConnect/lean-cli/blob/744a69be1b412d5ef2f4018815251a5f0e973168/lean/commands/cloud/live.py#L167-L169). Therefore, we can only select the IB data feed or the QC data feed. We should also be able to select the [hybrid IB-QC data feed](https://www.quantconnect.com/docs/v2/our-platform/live-trading/data-feeds/brokerage-data-feeds/interactive-brokers#06-Hybrid-QuantConnect-Data-Feed) since it's available in the cloud.

**Comment by DerekMelchin** [comment]
The [Tradier data feed](https://www.quantconnect.com/docs/v2/our-platform/live-trading/data-feeds/brokerage-data-feeds/tradier) also isn't supported.

**Comment by connorjohnlind** [comment]
Any timeline on resolving this issue?

**Comment by tochenliqun** [comment]
Need it available ASAP Pls
