### ISSUE TITLE
`lean cloud live` doesn't validate brokerage credentials

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#82]
If you enter incorrect brokerage credentials, the CLI doesn't show an error. It displays the live URL and members need to navigate to the site to see if their deployment was successful. 

For example, if you enter an invalid account tier for FTX, the command line makes it seem like the deployment was successful. However, you only see that there was an issue after you open the website.

> Algorithm.Initialize() Error: tier (Parameter 'ftxus Tier passed cannot be recognized. Please use one of the following values: Tier1,Tier2,Tier3,Tier4,Tier5,Tier6,Tier7,Tier8,Tier9,VIP1,VIP2,VIP3,MM1,MM2,MM3') Stack Trace: tier (Parameter 'ftxus Tier passed cannot be recognized. Please use one of the following values: Tier1,Tier2,Tier3,Tier4,Tier5,Tier6,Tier7,Tier8,Tier9,VIP1,VIP2,VIP3,MM1,MM2,MM3'): StackTrace: tier (Parameter 'ftxus Tier passed cannot be recognized. Please use one of the following values: Tier1,Tier2,Tier3,Tier4,Tier5,Tier6,Tier7,Tier8,Tier9,VIP1,VIP2,VIP3,MM1,MM2,MM3')

**Comment by Martin-Molinero** [comment]
Validating brokerage credentials isn't really available in the cloud either since we need to run Lean, connect to the brokerage and all. But this seems like a bug in the suggested tier options for Ftxus

**Comment by rjra2611** [comment]
solved by https://github.com/QuantConnect/lean-cli/pull/91
Previously, it was using `click.prompt( type=str)` . Now it's using `click.prompt( type=click.Choice())` therefore user will only be able to select from provided options
 
![image](https://user-images.githubusercontent.com/28739120/171728249-051ff989-bf3a-42c7-b2aa-fe8411a13af5.png)
