### ISSUE TITLE
`lean build` Shouldn't Deal With Alpha Streams

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/lean-cli#84]
It should just deal with the LEAN repo.

Related docs:
- [Building Custom Images](https://www.quantconnect.com/docs/v2/lean-cli/projects/custom-docker-images#03-Building-Custom-Images)
- [API Reference > lean build](https://www.quantconnect.com/docs/v2/lean-cli/api-reference/lean-build)

**Comment by Martin-Molinero** [comment]
Believe this is because alpha streams is a required dependency of Lean build process, see https://github.com/QuantConnect/Lean/blob/master/Dockerfile#L22, not sure it's a CLI issue?
