### ISSUE TITLE
C# Project Library Error

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/lean-cli#86]
The problem described in [this forum](https://www.quantconnect.com/forum/discussion/13228/code-sharing-between-different-projects-with-c-in-local-and-cloud-development/p1) post is reproducible. Following the tutorial from [CLI's docs](https://www.quantconnect.com/docs/v2/lean-cli/projects/libraries/project-libraries) will yield the same error.

**Comment by rjra2611** [comment]
Local code sharing was fixed by https://github.com/QuantConnect/lean-cli/pull/96 for both C# and python projects. 
Please follow the docs here for code sharing: https://www.quantconnect.com/docs/v2/lean-cli/projects/libraries/project-libraries

Currently, code sharing in the cloud is not supported

**Comment by Martin-Molinero** [comment]
This issue is solved already, see https://github.com/QuantConnect/lean-cli/pull/175, https://github.com/QuantConnect/lean-cli/pull/191, https://github.com/QuantConnect/lean-cli/pull/197, https://github.com/QuantConnect/lean-cli/pull/207, https://github.com/QuantConnect/lean-cli/pull/208
